# Generated by Django 5.1.6 on 2025-02-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Arquivo de áudio processado', upload_to='tracks/', verbose_name='Arquivo de áudio'),
        ),
    ]
